# Tiny configuration for local testing on MacBook Pro
# GPT-2 small model for fast iteration

model:
  type: "gpt2"
  name: "gpt2"
  hidden_size: 768
  num_layers: 4
  num_programs: 8
  alpha_cap: 0.05

constraints:
  grammar:
    enabled: true
    target: 0.0
    normalizer: "rank"
  graph2graph:
    enabled: true
    target: 0.2
    normalizer: "rank"

training:
  batch_size: 2
  learning_rate: 1e-4
  eta_lambda: 1e-2
  lambda_max: 10.0
  num_epochs: 5
  save_every: 2

data:
  max_length: 256
  vocab_size: 50257

runtime:
  max_generation_length: 50
  temperature: 0.8
  use_grammar_mask: true
